<?php
session_start();
require_once "../../classes/Analytics.php";
require_once "../../classes/Ticket.php";

if (!isset($_SESSION['user_id']) || $_SESSION['user_type'] !== 'admin') {
    header("Location: ../login.php");
    exit;
}

$analyticsObj = new Analytics();
$ticketObj = new Ticket();

$reportType = $_GET['type'] ?? 'summary';
$dateFrom = $_GET['date_from'] ?? date('Y-m-d', strtotime('-30 days'));
$dateTo = $_GET['date_to'] ?? date('Y-m-d');

$analytics = $analyticsObj->getTicketAnalytics($dateFrom, $dateTo);
$providerPerformance = $analyticsObj->getProviderPerformance();
$departmentPerformance = $analyticsObj->getDepartmentPerformance();
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Ticket Report - <?= date('M d, Y', strtotime($dateFrom)) ?> to <?= date('M d, Y', strtotime($dateTo)) ?></title>
<link rel="stylesheet" href="../../assets/css/theme.css">
<script>
    const PHP_SESSION_THEME = <?= json_encode($_SESSION['theme'] ?? 'light') ?>;
</script>
<style>
@media print {
    .no-print { display: none; }
    body { margin: 0; }
}

* { margin: 0; padding: 0; box-sizing: border-box; }

body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    padding: 40px;
    background: #fff;
    color: #333;
}

.report-header {
    text-align: center;
    border-bottom: 3px solid #667eea;
    padding-bottom: 20px;
    margin-bottom: 40px;
}

.company-name {
    font-size: 32px;
    font-weight: 700;
    color: #667eea;
    margin-bottom: 8px;
}

.report-title {
    font-size: 24px;
    color: #333;
    margin-bottom: 8px;
}

.report-period {
    color: #666;
    font-size: 14px;
}

.report-meta {
    display: flex;
    justify-content: space-between;
    margin-bottom: 40px;
    font-size: 13px;
    color: #666;
}

.section {
    margin-bottom: 40px;
}

.section-title {
    font-size: 20px;
    font-weight: 700;
    color: #667eea;
    margin-bottom: 20px;
    padding-bottom: 10px;
    border-bottom: 2px solid #e0e0e0;
}

.stats-grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 20px;
    margin-bottom: 30px;
}

.stat-box {
    border: 1px solid #e0e0e0;
    border-radius: 8px;
    padding: 20px;
    text-align: center;
}

.stat-value {
    font-size: 36px;
    font-weight: 700;
    color: #667eea;
    margin-bottom: 8px;
}

.stat-label {
    font-size: 14px;
    color: #666;
}

table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 30px;
}

th {
    background: #f8f9fa;
    padding: 12px;
    text-align: left;
    font-weight: 600;
    font-size: 13px;
    text-transform: uppercase;
    color: #666;
    border-bottom: 2px solid #667eea;
}

td {
    padding: 12px;
    border-bottom: 1px solid #e0e0e0;
    font-size: 14px;
}

tr:hover {
    background: #f8f9fa;
}

.report-footer {
    margin-top: 60px;
    padding-top: 20px;
    border-top: 2px solid #e0e0e0;
    text-align: center;
    font-size: 12px;
    color: #999;
}

.print-btn {
    position: fixed;
    top: 20px;
    right: 20px;
    padding: 12px 24px;
    background: linear-gradient(135deg, #667eea, #764ba2);
    color: white;
    border: none;
    border-radius: 8px;
    font-weight: 600;
    cursor: pointer;
    box-shadow: 0 4px 6px rgba(0,0,0,0.1);
}

.print-btn:hover {
    transform: translateY(-2px);
    box-shadow: 0 6px 12px rgba(0,0,0,0.15);
}

@media print {
    @page { margin: 20mm; }
    .stats-grid { grid-template-columns: repeat(2, 1fr); }
}
</style>
</head>
<body>

<button class="print-btn no-print" onclick="window.print()">🖨️ Print Report</button>

<div class="report-header">
    <div class="company-name">NEXON IT TICKETING SYSTEM</div>
    <div class="report-title">Ticket Analytics Report</div>
    <div class="report-period">
        Period: <?= date('F d, Y', strtotime($dateFrom)) ?> - <?= date('F d, Y', strtotime($dateTo)) ?>
    </div>
</div>

<div class="report-meta">
    <div>Report Generated: <?= date('F d, Y g:i A') ?></div>
    <div>Generated By: <?= htmlspecialchars($_SESSION['email']) ?></div>
</div>

<!-- Executive Summary -->
<div class="section">
    <h2 class="section-title">Executive Summary</h2>
    <div class="stats-grid">
        <div class="stat-box">
            <div class="stat-value"><?= count($analytics['daily_creation']) ?></div>
            <div class="stat-label">Total Tickets</div>
        </div>
        <div class="stat-box">
            <div class="stat-value"><?= $analytics['avg_resolution_hours'] ?>h</div>
            <div class="stat-label">Avg Resolution Time</div>
        </div>
        <div class="stat-box">
            <div class="stat-value"><?= count($analytics['by_status']) ?></div>
            <div class="stat-label">Status Categories</div>
        </div>
        <div class="stat-box">
            <div class="stat-value"><?= count($providerPerformance) ?></div>
            <div class="stat-label">Active Providers</div>
        </div>
    </div>
</div>

<!-- Tickets by Status -->
<div class="section">
    <h2 class="section-title">Tickets by Status</h2>
    <table>
        <thead>
            <tr>
                <th>Status</th>
                <th>Count</th>
                <th>Percentage</th>
            </tr>
        </thead>
        <tbody>
            <?php 
            $total = array_sum(array_column($analytics['by_status'], 'count'));
            foreach ($analytics['by_status'] as $item): 
                $percentage = $total > 0 ? ($item['count'] / $total) * 100 : 0;
            ?>
            <tr>
                <td style="text-transform:capitalize"><strong><?= str_replace('_', ' ', $item['status']) ?></strong></td>
                <td><?= $item['count'] ?></td>
                <td><?= number_format($percentage, 1) ?>%</td>
            </tr>
            <?php endforeach; ?>
            <tr style="background:#f8f9fa; font-weight:600">
                <td>TOTAL</td>
                <td><?= $total ?></td>
                <td>100%</td>
            </tr>
        </tbody>
    </table>
</div>

<!-- Tickets by Priority -->
<div class="section">
    <h2 class="section-title">Tickets by Priority</h2>
    <table>
        <thead>
            <tr>
                <th>Priority</th>
                <th>Count</th>
                <th>Percentage</th>
            </tr>
        </thead>
        <tbody>
            <?php 
            $priorityTotal = array_sum(array_column($analytics['by_priority'], 'count'));
            foreach ($analytics['by_priority'] as $item): 
                $percentage = $priorityTotal > 0 ? ($item['count'] / $priorityTotal) * 100 : 0;
            ?>
            <tr>
                <td style="text-transform:capitalize"><strong><?= $item['priority'] ?></strong></td>
                <td><?= $item['count'] ?></td>
                <td><?= number_format($percentage, 1) ?>%</td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<!-- Service Provider Performance -->
<div class="section">
    <h2 class="section-title">Service Provider Performance</h2>
    <table>
        <thead>
            <tr>
                <th>Provider</th>
                <th>Total Tickets</th>
                <th>Resolved</th>
                <th>Resolution Rate</th>
                <th>Avg Time (hrs)</th>
                <th>Rating</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($providerPerformance as $provider): 
                $resolutionRate = $provider['total_tickets'] > 0 ? 
                    ($provider['resolved_tickets'] / $provider['total_tickets']) * 100 : 0;
            ?>
            <tr>
                <td><strong><?= htmlspecialchars($provider['provider_name']) ?></strong></td>
                <td><?= $provider['total_tickets'] ?></td>
                <td><?= $provider['resolved_tickets'] ?></td>
                <td><?= number_format($resolutionRate, 1) ?>%</td>
                <td><?= number_format($provider['avg_resolution_hours'] ?? 0, 1) ?></td>
                <td><?= number_format($provider['rating_average'], 1) ?>★ (<?= $provider['total_ratings'] ?>)</td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<!-- Department Performance -->
<div class="section">
    <h2 class="section-title">Department Performance</h2>
    <table>
        <thead>
            <tr>
                <th>Department</th>
                <th>Category</th>
                <th>Total Tickets</th>
                <th>Resolved</th>
                <th>Pending</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($departmentPerformance as $dept): ?>
            <tr>
                <td><strong><?= htmlspecialchars($dept['department_name']) ?></strong></td>
                <td><?= htmlspecialchars($dept['category']) ?></td>
                <td><?= $dept['total_tickets'] ?></td>
                <td><?= $dept['resolved_tickets'] ?></td>
                <td><?= $dept['pending_tickets'] ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<!-- Top Departments by Volume -->
<div class="section">
    <h2 class="section-title">Top Departments by Ticket Volume</h2>
    <table>
        <thead>
            <tr>
                <th>Rank</th>
                <th>Department</th>
                <th>Total Tickets</th>
            </tr>
        </thead>
        <tbody>
            <?php 
            $rank = 1;
            foreach (array_slice($analytics['by_department'], 0, 10) as $dept): 
            ?>
            <tr>
                <td><strong>#<?= $rank++ ?></strong></td>
                <td><?= htmlspecialchars($dept['name']) ?></td>
                <td><?= $dept['count'] ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="report-footer">
    <p><strong>Nexon IT Ticketing System</strong> | Confidential Report</p>
    <p>This document contains proprietary information and is for internal use only.</p>
</div>
<script src="../../assets/js/theme.js"></script>
<script src="../../assets/js/notifications.js"></script>
</body>
</html>